[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#003087"
backgroundColor = "#f2f4f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
